### ISSUE TITLE
COCO-Stuff Evaluation

### ISSUE THREAD

**Issue by OasisArtisan** [sinahmr/NACLIP#1]
Hello, I wanted to understand the evaluation protocol you are using for COCO-stuff

It seems in https://github.com/sinahmr/NACLIP/blob/0cac3a651f753b11315ea799cfbfabf79da1bd76/datasets/cvt_coco_object.py#L192-L198

You are setting all stuff categories to background. In that case how is COCO-Stuff different from COCO-obj ?

**Comment by sinahmr** [comment]
Hi,
Yes, you are right.

**Comment by OasisArtisan** [comment]
I see, so the results reported in table 1 in the paper under C-Stf only include "thing" categories ?

**Comment by sinahmr** [comment]
C-Sft evaluates on all _thing_ and _stuff_ classes, while in C-Obj, we only have _thing_ categories and a background class.
